### ISSUE TITLE
Выбор прямоугольной области

### ISSUE THREAD

**Issue by spogozhev** [Godis715/Markup-Tool#6]
Если на изображении пользователю не представляется возможным выбрать прямоугольную область, то нет возможности перейти к следующему занятию. Может быть делать кнопку сохранения ответа активной даже если область не выделена?

**Comment by Godis715** [comment]
Думаю, стоит по умолчанию добавить кнопку, которую пользователь должен нажать, чтобы как-то отправить отметку, что требуемую область указать

**Comment by Godis715** [comment]
Сделано
