### ISSUE TITLE
Выбор нескольких областей

### ISSUE THREAD

**Issue by spogozhev** [Godis715/Markup-Tool#7]
Добавить возможность выбора нескольких прямоугольных областей на изображении.

**Comment by Godis715** [comment]
Сделано. Отдельный пулл реквест для этого не создавал, но вот добавленные возможности:
- Выделение нескольких прямоугольных областей
- Возможность удаления каждой отдельной области
- Возможность удаления сразу всех областей
- Кнопка "объектов нет"
